name: angular_app
description: A web app that uses AngularDart
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^0.14.0-alpha

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.1.1
  test: ^1.6.4
  pedantic: ^1.7.0
